/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar sesión con correo institucional */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Sesión iniciada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                401: components["responses"]["NoAutenticado"];
                422: components["responses"]["Validacion"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuario de la sesión actual */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                401: components["responses"]["NoAutenticado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cerrar sesión (invalida el token) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sesión cerrada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cursos del usuario (docente o estudiante) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Curso"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/{cursoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: components["parameters"]["cursoId"];
            };
            cookie?: never;
        };
        /** Detalle del curso */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cursoId: components["parameters"]["cursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Curso"];
                    };
                };
                403: components["responses"]["Prohibido"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/{cursoId}/estudiantes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: components["parameters"]["cursoId"];
            };
            cookie?: never;
        };
        /** Estudiantes inscritos (solo docente) */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["page"];
                    size?: components["parameters"]["size"];
                };
                header?: never;
                path: {
                    cursoId: components["parameters"]["cursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pagina"] & {
                            items?: components["schemas"]["UsuarioResumen"][];
                        };
                    };
                };
                403: components["responses"]["Prohibido"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/{cursoId}/raes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: components["parameters"]["cursoId"];
            };
            cookie?: never;
        };
        /** Resultados de Aprendizaje Esperados del syllabus */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cursoId: components["parameters"]["cursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rae"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/{cursoId}/temas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: components["parameters"]["cursoId"];
            };
            cookie?: never;
        };
        /** Temas y subtemas del syllabus */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cursoId: components["parameters"]["cursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tema"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/{cursoId}/tareas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: components["parameters"]["cursoId"];
            };
            cookie?: never;
        };
        /** Tareas del curso */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cursoId: components["parameters"]["cursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tarea"][];
                    };
                };
            };
        };
        put?: never;
        /** Crear tarea con criterios, rúbrica y casos de prueba (solo docente) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cursoId: components["parameters"]["cursoId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TareaCrear"];
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tarea"];
                    };
                };
                403: components["responses"]["Prohibido"];
                422: components["responses"]["Validacion"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tareas/{tareaId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tareaId: components["parameters"]["tareaId"];
            };
            cookie?: never;
        };
        /**
         * Detalle de la tarea
         * @description El estudiante no recibe `casosPrueba` ocultos ni la `rubrica` interna.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tareaId: components["parameters"]["tareaId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tarea"];
                    };
                };
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar criterios o configuración (solo docente)
         * @description No altera análisis ya generados; aplica a entregas nuevas.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tareaId: components["parameters"]["tareaId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TareaCrear"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tarea"];
                    };
                };
                403: components["responses"]["Prohibido"];
            };
        };
        trace?: never;
    };
    "/tareas/{tareaId}/resumen": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tareaId: components["parameters"]["tareaId"];
            };
            cookie?: never;
        };
        /** Métricas del tablero docente para la tarea */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tareaId: components["parameters"]["tareaId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResumenTarea"];
                    };
                };
                403: components["responses"]["Prohibido"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tareas/{tareaId}/entregas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tareaId: components["parameters"]["tareaId"];
            };
            cookie?: never;
        };
        /**
         * Entregas de la tarea (solo docente)
         * @description Devuelve la colección completa, de la más reciente a la más antigua, sin parámetros en la URL.
         *     La cola "por revisar" es el filtro `estado === "pendiente_revision"` que hace el frontend.
         *     A escala de un curso (~40 estudiantes × intentos) el tamaño es manejable.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tareaId: components["parameters"]["tareaId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntregaResumen"][];
                    };
                };
                403: components["responses"]["Prohibido"];
            };
        };
        put?: never;
        /**
         * Subir código (entrega oficial o revisión previa) — solo estudiante
         * @description Responde 202 de inmediato. El análisis se dispara solo (RF-16), sin intervención manual.
         *     Si el componente de IA falla, la entrega queda guardada con estado `error_analisis` (RNF-14).
         *     Una entrega `oficial` consume un intento; una `revision` no.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tareaId: components["parameters"]["tareaId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EntregaCrear"];
                };
            };
            responses: {
                /** @description Recibida; el análisis corre en segundo plano */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntregaEstudiante"];
                    };
                };
                403: components["responses"]["Prohibido"];
                /** @description Intentos agotados (`INTENTOS_AGOTADOS`) o tarea cerrada (`TAREA_CERRADA`) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Archivos exceden el tamaño máximo */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                422: components["responses"]["Validacion"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tareas/{tareaId}/intentos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tareaId: components["parameters"]["tareaId"];
            };
            cookie?: never;
        };
        /**
         * Historial de intentos de un estudiante en la tarea
         * @description El estudiante solo ve los suyos (se ignora `estudianteId`). El docente debe enviar `estudianteId`.
         */
        get: {
            parameters: {
                query?: {
                    estudianteId?: string;
                };
                header?: never;
                path: {
                    tareaId: components["parameters"]["tareaId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK, del más reciente al más antiguo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Intento"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entregas/{entregaId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entregaId: components["parameters"]["entregaId"];
            };
            cookie?: never;
        };
        /**
         * Detalle de una entrega
         * @description La respuesta depende del rol:
         *     - Docente → `EntregaDocente` (incluye análisis y borrador).
         *     - Estudiante dueño → `EntregaEstudiante` (solo retroalimentación publicada; nunca el borrador).
         *     - Cualquier otro → 403 (RNF-03).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entregaId: components["parameters"]["entregaId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntregaDocente"] | components["schemas"]["EntregaEstudiante"];
                    };
                };
                403: components["responses"]["Prohibido"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entregas/{entregaId}/archivos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entregaId: components["parameters"]["entregaId"];
            };
            cookie?: never;
        };
        /** Código fuente entregado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entregaId: components["parameters"]["entregaId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArchivoCodigo"][];
                    };
                };
                403: components["responses"]["Prohibido"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entregas/{entregaId}/reanalizar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entregaId: components["parameters"]["entregaId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reintentar el análisis tras un fallo de IA (solo docente) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entregaId: components["parameters"]["entregaId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reencolada */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntregaDocente"];
                    };
                };
                409: components["responses"]["EstadoInvalido"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entregas/{entregaId}/retroalimentacion": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entregaId: components["parameters"]["entregaId"];
            };
            cookie?: never;
        };
        /** Borrador generado para revisión (solo docente) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entregaId: components["parameters"]["entregaId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Retroalimentacion"];
                    };
                };
                403: components["responses"]["Prohibido"];
                /** @description El análisis aún no termina (`ANALISIS_EN_CURSO`) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar el borrador y/o el comentario del docente
         * @description Solo en estado `pendiente_revision`. Si el origen era `ia`, pasa a `ia_editada`.
         *     Registra un evento de auditoría `editar`.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entregaId: components["parameters"]["entregaId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RetroalimentacionEditar"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Retroalimentacion"];
                    };
                };
                409: components["responses"]["EstadoInvalido"];
                422: components["responses"]["Validacion"];
            };
        };
        trace?: never;
    };
    "/entregas/{entregaId}/retroalimentacion/descartar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entregaId: components["parameters"]["entregaId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Descartar el borrador de IA y escribir desde cero
         * @description Vacía las secciones generadas, marca `origen = docente` y deja la entrega en `pendiente_revision`
         *     para que el docente redacte con PATCH y luego apruebe. Registra evento `descartar`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entregaId: components["parameters"]["entregaId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Opcional; útil para mejorar el prompt */
                        motivo?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Retroalimentacion"];
                    };
                };
                409: components["responses"]["EstadoInvalido"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entregas/{entregaId}/retroalimentacion/aprobar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entregaId: components["parameters"]["entregaId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aprobar y enviar al estudiante
         * @description Única vía por la que la retroalimentación se vuelve visible para el estudiante.
         *     Pasa la entrega a `enviada`, fija `fechaEnvio`, notifica al estudiante y registra evento `aprobar`.
         *     Rechaza con 422 si `queSigue` está vacío (RF-03).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entregaId: components["parameters"]["entregaId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Enviada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntregaDocente"];
                    };
                };
                409: components["responses"]["EstadoInvalido"];
                422: components["responses"]["Validacion"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entregas/{entregaId}/calificacion": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entregaId: components["parameters"]["entregaId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Registrar la nota sumativa (solo docente, separada del feedback)
         * @description Recurso independiente de la retroalimentación. La IA no propone ni escribe este valor.
         *     Alimenta los reportes de trayectoria (eje X).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entregaId: components["parameters"]["entregaId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Calificacion"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Calificacion"];
                    };
                };
                403: components["responses"]["Prohibido"];
                422: components["responses"]["Validacion"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entregas/{entregaId}/auditoria": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entregaId: components["parameters"]["entregaId"];
            };
            cookie?: never;
        };
        /** Registro de intervenciones sobre la retroalimentación */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entregaId: components["parameters"]["entregaId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK, en orden cronológico */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventoAuditoria"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estudiantes/me/cursos/{cursoId}/tareas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: components["parameters"]["cursoId"];
            };
            cookie?: never;
        };
        /**
         * Mis entregas (tareas del curso con su estado para el estudiante de la sesión)
         * @description El estudiante se identifica por el token; el curso, por la ruta.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cursoId: components["parameters"]["cursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK, ordenadas por fecha límite */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TareaEstudiante"][];
                    };
                };
                403: components["responses"]["Prohibido"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estudiantes/me/cursos/{cursoId}/progreso": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: components["parameters"]["cursoId"];
            };
            cookie?: never;
        };
        /**
         * Mi progreso en el curso
         * @description El estudiante se identifica por el token; el curso, por la ruta.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cursoId: components["parameters"]["cursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProgresoEstudiante"];
                    };
                };
                403: components["responses"]["Prohibido"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entregas/{entregaId}/retroalimentacion/leida": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entregaId: components["parameters"]["entregaId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marcar la retroalimentación como leída */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entregaId: components["parameters"]["entregaId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["EstadoInvalido"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entregas/{entregaId}/dudas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entregaId: components["parameters"]["entregaId"];
            };
            cookie?: never;
        };
        /** Dudas del estudiante sobre esta retroalimentación */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entregaId: components["parameters"]["entregaId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Duda"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Enviar una duda (estudiante)
         * @description La IA puede redactar un borrador de respuesta (RAG sobre syllabus y banco de ejercicios),
         *     pero la respuesta sigue el mismo flujo de aprobación docente que la retroalimentación (RNF-06).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entregaId: components["parameters"]["entregaId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        pregunta: string;
                    };
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Duda"];
                    };
                };
                409: components["responses"]["EstadoInvalido"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dudas/{dudaId}/responder": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dudaId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aprobar (con o sin edición) la respuesta a una duda (docente) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dudaId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        respuesta: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Duda"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/{cursoId}/reportes/trayectoria": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: components["parameters"]["cursoId"];
            };
            cookie?: never;
        };
        /**
         * Mapa de desempeño vs. dificultad por RAE o tema y corte (solo docente)
         * @description Devuelve los puntos crudos por estudiante y la fricción comparada entre ítems.
         *     Los agregados (clusters, delta, % en riesgo) los calcula el frontend como en el mockup
         *     en el MVP; los umbrales vienen en `umbrales` para no quemarlos en dos lados.
         */
        get: {
            parameters: {
                query: {
                    dimension: "rae" | "tema";
                    /** @description ID del RAE o tema seleccionado */
                    itemId: string;
                    corte: components["schemas"]["Corte"];
                };
                header?: never;
                path: {
                    cursoId: components["parameters"]["cursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReporteTrayectoria"];
                    };
                };
                403: components["responses"]["Prohibido"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/{cursoId}/reportes/errores-frecuentes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: components["parameters"]["cursoId"];
            };
            cookie?: never;
        };
        /** Errores más frecuentes del curso (solo docente) */
        get: {
            parameters: {
                query?: {
                    tareaId?: string;
                    limite?: number;
                };
                header?: never;
                path: {
                    cursoId: components["parameters"]["cursoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK, ordenados por ocurrencias desc */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorFrecuente"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notificaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notificaciones del usuario */
        get: {
            parameters: {
                query?: {
                    noLeidas?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Número del badge */
                            noLeidas: number;
                            items: components["schemas"]["Notificacion"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notificaciones/{notificacionId}/leida": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificacionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marcar notificación como leída */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    notificacionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /**
                 * @example ESTADO_INVALIDO
                 * @example INTENTOS_AGOTADOS
                 * @example TAREA_CERRADA
                 * @example ANALISIS_EN_CURSO
                 * @example VALIDACION
                 */
                codigo: string;
                /** @description Texto mostrable al usuario */
                mensaje: string;
                detalles?: {
                    campo?: string;
                    problema?: string;
                }[];
            };
        };
        Pagina: {
            items: unknown[];
            total: number;
            page: number;
            size: number;
        };
        /**
         * @description `monitor` (actor secundario) queda fuera del MVP
         * @enum {string}
         */
        Rol: "docente" | "estudiante";
        /** @enum {string} */
        Corte: "I" | "II" | "III";
        LoginRequest: {
            /** Format: email */
            correo: string;
            /** Format: password */
            contrasena: string;
            /** @default false */
            mantenerSesion: boolean;
        };
        LoginResponse: {
            token: string;
            /** Format: date-time */
            expiraEn: string;
            usuario: components["schemas"]["Usuario"];
        };
        Usuario: {
            /** Format: uuid */
            id: string;
            /** @example Pepito Perez */
            nombre: string;
            /** Format: email */
            correo: string;
            rol: components["schemas"]["Rol"];
            /** @example PP */
            iniciales: string;
        };
        UsuarioResumen: {
            /** Format: uuid */
            id: string;
            nombre: string;
            /**
             * Format: email
             * @description Solo visible para el docente del curso
             */
            correo?: string;
        };
        Curso: {
            /** Format: uuid */
            id: string;
            /** @example Introducción a la Programación */
            nombre: string;
            /** @example 2026-1 */
            periodo: string;
            /** @example 8 */
            semanaActual?: number;
            /** @example 16 */
            semanasTotales?: number;
            docentes?: components["schemas"]["UsuarioResumen"][];
        };
        Rae: {
            /** @example 1 */
            id: string;
            /** @example Caracterizar problemas */
            corto: string;
            texto: string;
            /** @example Disciplinar 1 · CDIO 2.1 */
            etiquetas?: string;
        };
        Tema: {
            /** @example 3 */
            id: string;
            /** @example Manejo de memoria con colecciones de datos */
            titulo: string;
            subtemas: string[];
        };
        CasoPrueba: {
            /** Format: uuid */
            readonly id?: string;
            nombre: string;
            /** @description stdin */
            entrada: string;
            /** @description stdout esperado */
            salidaEsperada: string;
            /**
             * @description Si es false, el estudiante solo ve si pasó o no, nunca la salida esperada (RF-09)
             * @default false
             */
            visibleEstudiante: boolean;
        };
        /** @description Qué dimensiones analiza la IA (RF-04..RF-07, RF-14) */
        CriteriosEvaluacion: {
            /** @default true */
            correccionFuncional: boolean;
            /** @default true */
            legibilidad: boolean;
            /** @default true */
            mantenibilidad: boolean;
            /** @default false */
            documentacion: boolean;
            /** @description Texto libre del docente que se inyecta en el prompt */
            instruccionesAdicionales?: string;
        };
        TareaCrear: {
            /** @example Tarea 4 — Promedio de un arreglo */
            titulo: string;
            enunciado?: string;
            /**
             * @example cpp
             * @enum {string}
             */
            lenguaje: "cpp" | "c" | "python" | "java";
            /** Format: date-time */
            fechaLimite: string;
            /** @example 3 */
            maxIntentos: number;
            corte?: components["schemas"]["Corte"];
            raeIds?: string[];
            temaIds?: string[];
            criterios?: components["schemas"]["CriteriosEvaluacion"];
            /** @description Markdown. Guía la retroalimentación, NO produce puntaje (RF-15, RF-17) */
            rubrica?: string;
            casosPrueba?: components["schemas"]["CasoPrueba"][];
            /**
             * @description Habilita el botón "Revisar mi código" (entregas tipo `revision`)
             * @default true
             */
            permitirRevisionPrevia: boolean;
        };
        Tarea: components["schemas"]["TareaCrear"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            cursoId: string;
            /** @enum {string} */
            estado: "borrador" | "abierta" | "cerrada";
        };
        ResumenTarea: {
            /** @example 41 */
            estudiantes: number;
            /** @example 21 */
            entregasRecibidas: number;
            /** @example 16 */
            pendientesRevision: number;
            /**
             * @description Promedio de (fechaEnvio - fechaEntrega) de entregas oficiales enviadas (RNF-11)
             * @example 4.2
             */
            tiempoMedioRespuestaHoras: number | null;
            /** @description Tiempo que el docente tarda por entrega (RNF-08). Medido entre abrir y aprobar. */
            tiempoMedioRevisionDocenteMin?: number | null;
        };
        /**
         * @description recibida → en_analisis → pendiente_revision → enviada
         *     en_analisis → error_analisis → (reanalizar) → en_analisis
         *     Mapeo al pipeline del mockup: Entrega recibida / Análisis realizado / Feedback generado / Feedback enviado.
         * @enum {string}
         */
        EstadoEntrega: "recibida" | "en_analisis" | "pendiente_revision" | "enviada" | "error_analisis";
        /**
         * @description `revision` = "Subir código para revisión, sin entregar"; no consume intento
         * @enum {string}
         */
        TipoEntrega: "oficial" | "revision";
        ArchivoCodigoCrear: {
            /** @example promedio_notas.cpp */
            nombre: string;
            /** @description Texto UTF-8. Máx. propuesto: 200 KB en total por entrega */
            contenido: string;
        };
        ArchivoCodigo: components["schemas"]["ArchivoCodigoCrear"] & {
            lenguaje?: string;
            lineas?: number;
        };
        EntregaCrear: {
            tipo: components["schemas"]["TipoEntrega"];
            archivos: components["schemas"]["ArchivoCodigoCrear"][];
            /**
             * @description Autorreporte del estudiante. Lo exige el eje Y del reporte de trayectoria;
             *     NO está en los RF actuales (ver decisiones abiertas).
             */
            dificultadPercibida?: number;
        };
        EntregaResumen: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tareaId?: string;
            estudiante: components["schemas"]["UsuarioResumen"];
            tipo: components["schemas"]["TipoEntrega"];
            /**
             * @description null si tipo = revision
             * @example 2
             */
            numeroIntento: number | null;
            /** @example 3 */
            maxIntentos?: number;
            estado: components["schemas"]["EstadoEntrega"];
            /** Format: date-time */
            fechaEntrega: string;
            /** Format: date-time */
            fechaEnvio?: string | null;
        };
        LineaMarcada: {
            archivo: string;
            /** @example 9 */
            linea: number;
            /** @enum {string} */
            severidad: "error" | "advertencia" | "sugerencia";
            /** @example Índice fuera de rango */
            mensaje: string;
        };
        ResultadoPrueba: {
            nombre: string;
            aprobado: boolean;
            /** @description Solo si el caso es visible para el estudiante o quien consulta es docente */
            salidaObtenida?: string;
            /** @description Ídem */
            salidaEsperada?: string;
        };
        /** @description Salida técnica del análisis (no es la retroalimentación pedagógica) */
        ResultadoAnalisis: {
            compilacion?: {
                ok?: boolean;
                advertencias?: string[];
                errores?: string[];
            };
            /** @description RF-04 */
            pruebas?: {
                total?: number;
                aprobadas?: number;
                casos?: components["schemas"]["ResultadoPrueba"][];
            };
            /** @description RF-05, RF-06, RF-07 (null si el criterio está desactivado) */
            observaciones?: {
                legibilidad?: string | null;
                mantenibilidad?: string | null;
                documentacion?: string | null;
            };
            lineasMarcadas?: components["schemas"]["LineaMarcada"][];
            /**
             * @description Qué cambió respecto al intento anterior (alimenta el historial de intentos)
             * @example Corrigió el tipo de la variable acumuladora
             */
            resumenCambios?: string | null;
            /** @description Modelo de IA usado (trazabilidad, RV-03) */
            modelo?: string;
        };
        /** @description Estructura de Hattie & Timperley (RF-02). Sin campo de nota (RF-17). */
        SeccionesFeedback: {
            /** @description Meta de aprendizaje de la tarea */
            haciaDondeVoy: string;
            /** @description Estado actual del código frente a la meta */
            comoVoy: string;
            /** @description Obligatorio y prioritario (RF-03) */
            queSigue: string;
            /** @description Orientadas al razonamiento; no deben contener la solución (RF-08, RF-09) */
            pistas?: string[];
        };
        /**
         * @description RF-19. Se recalcula en el backend, el frontend no lo envía.
         * @enum {string}
         */
        OrigenFeedback: "ia" | "ia_editada" | "docente";
        /** @description Vista del docente (incluye el borrador). */
        Retroalimentacion: {
            /** Format: uuid */
            entregaId: string;
            /** @enum {string} */
            estado: "pendiente_revision" | "enviada";
            origen: components["schemas"]["OrigenFeedback"];
            secciones: components["schemas"]["SeccionesFeedback"];
            /** @description Texto libre del docente (en el mockup "Nota del docente"; ver decisiones abiertas) */
            comentarioDocente?: string | null;
            /** Format: date-time */
            generadoEn?: string;
            /** Format: date-time */
            actualizadoEn?: string;
        };
        RetroalimentacionEditar: {
            secciones?: components["schemas"]["SeccionesFeedback"];
            comentarioDocente?: string | null;
        };
        /** @description RF-18. Siempre presente en la retroalimentación publicada. */
        AvisoIA: {
            participoIA: boolean;
            /** @example EduTrace generó un borrador con IA; tu profesor lo revisó y aprobó. */
            texto: string;
        };
        /** @description Vista del estudiante. Solo existe si la entrega está `enviada`. */
        RetroalimentacionPublicada: {
            secciones: components["schemas"]["SeccionesFeedback"];
            comentarioDocente?: string | null;
            origen?: components["schemas"]["OrigenFeedback"];
            aviso: components["schemas"]["AvisoIA"];
            revisadoPor: components["schemas"]["UsuarioResumen"];
            /** Format: date-time */
            fechaEnvio: string;
            leida: boolean;
        };
        EntregaDocente: components["schemas"]["EntregaResumen"] & {
            archivos?: components["schemas"]["ArchivoCodigo"][];
            analisis?: components["schemas"]["ResultadoAnalisis"] | null;
            retroalimentacion?: components["schemas"]["Retroalimentacion"] | null;
            dificultadPercibida?: number | null;
            /** @description Mensaje si estado = error_analisis */
            errorAnalisis?: string | null;
        };
        EntregaEstudiante: components["schemas"]["EntregaResumen"] & {
            retroalimentacion?: components["schemas"]["RetroalimentacionPublicada"] | null;
            /** @description Solo resultados de casos visibles, y solo tras el envío */
            pruebas?: {
                total?: number;
                aprobadas?: number;
            } | null;
        };
        Calificacion: {
            /** @example 3.5 */
            nota: number;
            registradaPor?: components["schemas"]["UsuarioResumen"];
            /** Format: date-time */
            readonly fecha?: string;
        };
        EventoAuditoria: {
            /** Format: uuid */
            id: string;
            autor: components["schemas"]["UsuarioResumen"];
            /** @enum {string} */
            accion: "generar" | "editar" | "descartar" | "aprobar" | "reanalizar" | "calificar" | "responder_duda";
            /** Format: date-time */
            fecha: string;
            /** @description Diff o metadatos de la acción */
            detalle?: {
                [key: string]: unknown;
            };
        };
        Intento: {
            /** Format: uuid */
            entregaId: string;
            /**
             * @example Intento 2
             * @example Revisión
             */
            etiqueta: string;
            tipo?: components["schemas"]["TipoEntrega"];
            /** Format: date-time */
            fecha: string;
            /** @description = analisis.resumenCambios, solo si ya fue enviada */
            titulo?: string | null;
            /** @description Resumen corto del hallazgo principal (texto, NO calificación) */
            nota?: string | null;
            /** @enum {string} */
            estado: "en_revision" | "retroalimentado" | "sin_nota";
        };
        TareaEstudiante: {
            /** Format: uuid */
            tareaId: string;
            titulo: string;
            /** Format: date-time */
            fechaLimite: string;
            /** @enum {string} */
            estado: "pendiente" | "en_revision" | "retroalimentada" | "aprobada" | "vencida";
            intentosUsados?: number;
            maxIntentos?: number;
            /** Format: uuid */
            ultimaEntregaId?: string | null;
            /** Format: date-time */
            ultimaEntregaFecha?: string | null;
        };
        ProgresoEstudiante: {
            entregasAlDia: {
                /** @example 7 */
                hechas?: number;
                /** @example 9 */
                total?: number;
            };
            retroalimentacionesLeidas: {
                /** @example 6 */
                leidas?: number;
                /** @example 7 */
                total?: number;
            };
            /**
             * @description Líneas marcadas en el intento N que ya no aparecen en el N+1
             * @example 5
             */
            erroresCorregidos: number;
            /** @example 1.8 */
            intentosPromedio: number;
            /** @description "Dónde me cuesta más" */
            temas: {
                temaId: string;
                /** @example Arreglos y ciclos */
                titulo: string;
                /** @description Definición propuesta: entregas oficiales del tema con al menos una línea marcada como error */
                tropiezos: number;
                /** @enum {string} */
                nivel?: "alto" | "medio" | "bajo";
            }[];
        };
        Duda: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            entregaId: string;
            pregunta: string;
            /** @enum {string} */
            estado: "pendiente_revision" | "respondida";
            /** @description Solo visible para el docente */
            borradorRespuesta?: string | null;
            respuesta?: string | null;
            origen?: components["schemas"]["OrigenFeedback"];
            /** Format: date-time */
            fecha: string;
        };
        PuntoTrayectoria: {
            /** Format: uuid */
            estudianteId: string;
            nombre: string;
            /** @description Promedio de calificaciones del docente en el ítem y corte */
            nota: number;
            /** @description dificultadPercibida normalizada */
            dificultad: number;
            /** @description Posición en el corte anterior (null en corte I) */
            anterior?: {
                nota?: number;
                dificultad?: number;
            } | null;
            estancado: boolean;
            intentos: number;
            /** @description Intentos hasta nota ≥ 3.0; null si no la alcanza */
            intentosASuficiencia?: number | null;
            /**
             * @description Salto brusco de desempeño sin intentos intermedios. Es una señal para revisar,
             *     NO una acusación de copia o uso de IA (ver decisiones abiertas).
             */
            alertaRevision: boolean;
        };
        FriccionItem: {
            itemId: string;
            etiqueta: string;
            pctMasDeDosIntentos: number;
        };
        ReporteTrayectoria: {
            /** @enum {string} */
            dimension: "rae" | "tema";
            itemId: string;
            corte: components["schemas"]["Corte"];
            puntos: components["schemas"]["PuntoTrayectoria"][];
            friccionComparada: components["schemas"]["FriccionItem"][];
            /** @description Fuente única de los cortes que usa el frontend */
            umbrales: {
                /** @default 3 */
                notaAprobacion: number;
                /** @default 3.75 */
                notaAlta: number;
                /** @default 0.66 */
                dificultadAlta: number;
                /** @default 20 */
                friccionMedia: number;
                /** @default 40 */
                friccionAlta: number;
            };
        };
        ErrorFrecuente: {
            /** @example indice_fuera_de_rango */
            categoria: string;
            /** @example Condición de ciclo que accede fuera del arreglo */
            descripcion: string;
            ocurrencias: number;
            estudiantesAfectados: number;
            temaId?: string | null;
        };
        Notificacion: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            tipo: "retroalimentacion_disponible" | "entrega_por_revisar" | "duda_nueva" | "fallo_analisis";
            mensaje: string;
            enlace?: {
                /** @enum {string} */
                recurso?: "entrega" | "duda" | "tarea";
                /** Format: uuid */
                id?: string;
            };
            /** Format: date-time */
            fecha: string;
            leida: boolean;
        };
    };
    responses: {
        /** @description Falta token o es inválido */
        NoAutenticado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description El rol o el usuario no tiene acceso a este recurso */
        Prohibido: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No existe */
        NoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Datos inválidos */
        Validacion: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description La operación no aplica al estado actual (`ESTADO_INVALIDO`), p. ej. aprobar algo ya enviado */
        EstadoInvalido: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        cursoId: string;
        tareaId: string;
        entregaId: string;
        page: number;
        size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
